import type { Flower } from '$lib/types/flower';
import flowerImages from '../../../flora-fusion-images.json';

/**
 * FLOWER IMAGE SOURCING NOTE:
 * mainImage resolves to the catalog photo hosted on Cloudinary (see
 * flora-fusion-images.json at the project root). This lets the storefront
 * grid display real images out of the box, with no Firebase Storage upload
 * step required. If a matching entry is ever removed from that file, the
 * placeholder graphic is shown instead (see resolveStorageUrl()).
 */
function buildFlower(base: Omit<Flower, 'mainImage' | 'galleryImages' | 'reviews'>): Flower {
	const image = (flowerImages.flowers as Record<string, string>)[base.id] ?? '';

	return {
		...base,
		mainImage: image,
		galleryImages: [],
		reviews: []
	};
}

export const FLOWERS: Flower[] = [
	buildFlower({
		id: 'rose-hybrid-tea',
		commonName: 'Rose',
		botanicalName: 'Rosa × hybrida',
		scientificName: 'Rosa × hybrida',
		category: 'Rose Family',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Nilgiri Rose Growers Collective',
		country: 'India',
		availableStock: 480,
		remainingStock: 356,
		price: 449,
		description:
			'The hybrid tea rose is the gold standard of preservation flowers — full, layered blooms that hold their shape and color exceptionally well through silica gel drying.',
		preservationMethod: 'Silica Gel Drying',
		expectedPreservedLife: '3-5 years',
		colorCategory: 'Red',
		rating: 4.8,
		tags: ['romantic', 'wedding', 'classic', 'anniversary'],
		season: 'Year-Round',
		availability: true
	}),
	buildFlower({
		id: 'garden-rose',
		commonName: 'Garden Rose',
		botanicalName: 'Rosa gallica',
		scientificName: 'Rosa gallica',
		category: 'Rose Family',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Nilgiri Rose Growers Collective',
		country: 'India',
		availableStock: 300,
		remainingStock: 214,
		price: 529,
		description:
			'Dense, ruffled petals in soft heirloom tones make garden roses a favorite for keepsake resin work and pressed frame art.',
		preservationMethod: 'Resin Casting',
		expectedPreservedLife: '5+ years',
		colorCategory: 'Pink',
		rating: 4.9,
		tags: ['luxury', 'wedding', 'bouquet'],
		season: 'Spring',
		availability: true
	}),
	buildFlower({
		id: 'carnation',
		commonName: 'Carnation',
		botanicalName: 'Dianthus caryophyllus',
		scientificName: 'Dianthus caryophyllus',
		category: 'Rose Family',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Deccan Flower Farms',
		country: 'India',
		availableStock: 620,
		remainingStock: 501,
		price: 199,
		description:
			'Ruffled, long-lasting petals with a naturally sturdy structure make carnations ideal for beginner-friendly preservation and vibrant color retention.',
		preservationMethod: 'Silica Gel Drying',
		expectedPreservedLife: '3-4 years',
		colorCategory: 'Pink',
		rating: 4.5,
		tags: ['affordable', 'birthday', 'everyday'],
		season: 'Year-Round',
		availability: true
	}),
	buildFlower({
		id: 'hydrangea',
		commonName: 'Hydrangea',
		botanicalName: 'Hydrangea macrophylla',
		scientificName: 'Hydrangea macrophylla',
		category: 'Everlasting',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Blue Mountain Botanicals',
		country: 'India',
		availableStock: 260,
		remainingStock: 189,
		price: 389,
		description:
			'Cloud-like clusters of small florets that air-dry beautifully on their own, prized for large-format frame and dome keepsakes.',
		preservationMethod: 'Pressed Preservation',
		expectedPreservedLife: '4+ years',
		colorCategory: 'Blue',
		rating: 4.7,
		tags: ['statement', 'wedding', 'large-arrangement'],
		season: 'Summer',
		availability: true
	}),
	buildFlower({
		id: 'babys-breath',
		commonName: "Baby's Breath",
		botanicalName: 'Gypsophila paniculata',
		scientificName: 'Gypsophila paniculata',
		category: 'Filler Flower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Deccan Flower Farms',
		country: 'India',
		availableStock: 900,
		remainingStock: 812,
		price: 129,
		description:
			'Delicate, airy sprays that preserve almost indefinitely, commonly layered into bouquets and resin jewelry for texture.',
		preservationMethod: 'Pressed Preservation',
		expectedPreservedLife: '5+ years',
		colorCategory: 'White',
		rating: 4.6,
		tags: ['filler', 'wedding', 'delicate'],
		season: 'Year-Round',
		availability: true
	}),
	buildFlower({
		id: 'lavender',
		commonName: 'Lavender',
		botanicalName: 'Lavandula angustifolia',
		scientificName: 'Lavandula angustifolia',
		category: 'Herb Flower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Kashmir Aromatic Gardens',
		country: 'India',
		availableStock: 540,
		remainingStock: 470,
		price: 179,
		description:
			'Fragrant purple spikes that retain scent and color for years, popular for sachets, resin coasters, and calming keepsakes.',
		preservationMethod: 'Pressed Preservation',
		expectedPreservedLife: '4+ years',
		colorCategory: 'Purple',
		rating: 4.8,
		tags: ['aromatic', 'calming', 'gift'],
		season: 'Summer',
		availability: true
	}),
	buildFlower({
		id: 'chrysanthemum',
		commonName: 'Chrysanthemum',
		botanicalName: 'Chrysanthemum indicum',
		scientificName: 'Chrysanthemum indicum',
		category: 'Everlasting',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Nilgiri Rose Growers Collective',
		country: 'India',
		availableStock: 410,
		remainingStock: 355,
		price: 229,
		description:
			'Dense, multi-petaled blooms symbolizing longevity, well suited to freeze-drying for maximum shape retention.',
		preservationMethod: 'Freeze-Drying',
		expectedPreservedLife: '5+ years',
		colorCategory: 'Yellow',
		rating: 4.6,
		tags: ['longevity', 'memorial', 'traditional'],
		season: 'Autumn',
		availability: true
	}),
	buildFlower({
		id: 'orchid-phalaenopsis',
		commonName: 'Orchid',
		botanicalName: 'Phalaenopsis amabilis',
		scientificName: 'Phalaenopsis amabilis',
		category: 'Tropical',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Western Ghats Orchidarium',
		country: 'India',
		availableStock: 180,
		remainingStock: 122,
		price: 699,
		description:
			'Elegant, waxy petals that require careful freeze-drying to preserve their signature sheen and form.',
		preservationMethod: 'Freeze-Drying',
		expectedPreservedLife: '3-5 years',
		colorCategory: 'White',
		rating: 4.9,
		tags: ['exotic', 'luxury', 'elegant'],
		season: 'Year-Round',
		availability: true
	}),
	buildFlower({
		id: 'statice',
		commonName: 'Statice',
		botanicalName: 'Limonium sinuatum',
		scientificName: 'Limonium sinuatum',
		category: 'Everlasting',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Deccan Flower Farms',
		country: 'India',
		availableStock: 700,
		remainingStock: 645,
		price: 149,
		description:
			'A true "everlasting" flower — papery petals hold color naturally with minimal intervention, ideal for budget-friendly keepsakes.',
		preservationMethod: 'Pressed Preservation',
		expectedPreservedLife: '5+ years',
		colorCategory: 'Purple',
		rating: 4.4,
		tags: ['everlasting', 'colorful', 'budget'],
		season: 'Summer',
		availability: true
	}),
	buildFlower({
		id: 'peony',
		commonName: 'Peony',
		botanicalName: 'Paeonia lactiflora',
		scientificName: 'Paeonia lactiflora',
		category: 'Rose Family',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Himalayan Peony Growers',
		country: 'India',
		availableStock: 150,
		remainingStock: 98,
		price: 799,
		description:
			'Lush, voluminous blooms with silky petals — a premium choice for statement resin art and shadow-box keepsakes.',
		preservationMethod: 'Silica Gel Drying',
		expectedPreservedLife: '3-4 years',
		colorCategory: 'Pink',
		rating: 4.9,
		tags: ['premium', 'wedding', 'statement'],
		season: 'Spring',
		availability: true
	}),
	buildFlower({
		id: 'tulip',
		commonName: 'Tulip',
		botanicalName: 'Tulipa gesneriana',
		scientificName: 'Tulipa gesneriana',
		category: 'Bulb Flower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Kashmir Bulb Gardens',
		country: 'India',
		availableStock: 320,
		remainingStock: 240,
		price: 269,
		description:
			'Clean, cup-shaped blooms that press beautifully flat, favored for framed botanical art.',
		preservationMethod: 'Pressed Preservation',
		expectedPreservedLife: '3-4 years',
		colorCategory: 'Red',
		rating: 4.5,
		tags: ['spring', 'clean-lines', 'framed-art'],
		season: 'Spring',
		availability: true
	}),
	buildFlower({
		id: 'sunflower',
		commonName: 'Sunflower',
		botanicalName: 'Helianthus annuus',
		scientificName: 'Helianthus annuus',
		category: 'Bulb Flower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Deccan Flower Farms',
		country: 'India',
		availableStock: 210,
		remainingStock: 156,
		price: 349,
		description:
			'Bold, sunny blooms that dry well when de-petaled and pressed individually for vivid keepsake pieces.',
		preservationMethod: 'Pressed Preservation',
		expectedPreservedLife: '3+ years',
		colorCategory: 'Yellow',
		rating: 4.6,
		tags: ['cheerful', 'summer', 'bold'],
		season: 'Summer',
		availability: true
	}),
	buildFlower({
		id: 'lily-oriental',
		commonName: 'Oriental Lily',
		botanicalName: 'Lilium orientalis',
		scientificName: 'Lilium orientalis',
		category: 'Bulb Flower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Himalayan Peony Growers',
		country: 'India',
		availableStock: 190,
		remainingStock: 133,
		price: 459,
		description:
			'Large, fragrant petals with striking freckled detail; freeze-drying retains their dramatic curve and color.',
		preservationMethod: 'Freeze-Drying',
		expectedPreservedLife: '3-4 years',
		colorCategory: 'Pink',
		rating: 4.7,
		tags: ['fragrant', 'dramatic', 'gift'],
		season: 'Summer',
		availability: true
	}),
	buildFlower({
		id: 'marigold',
		commonName: 'Marigold',
		botanicalName: 'Tagetes erecta',
		scientificName: 'Tagetes erecta',
		category: 'Everlasting',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Deccan Flower Farms',
		country: 'India',
		availableStock: 800,
		remainingStock: 710,
		price: 99,
		description:
			'Vivid, ruffled blooms traditionally used in celebrations; naturally holds pigment through drying with little fading.',
		preservationMethod: 'Silica Gel Drying',
		expectedPreservedLife: '2-3 years',
		colorCategory: 'Orange',
		rating: 4.3,
		tags: ['festive', 'traditional', 'affordable'],
		season: 'Autumn',
		availability: true
	}),
	buildFlower({
		id: 'jasmine',
		commonName: 'Jasmine',
		botanicalName: 'Jasminum sambac',
		scientificName: 'Jasminum sambac',
		category: 'Herb Flower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Malabar Fragrant Farms',
		country: 'India',
		availableStock: 500,
		remainingStock: 402,
		price: 159,
		description:
			'Small, intensely fragrant white blossoms, delicate but well-suited to glycerin preservation for softness and scent retention.',
		preservationMethod: 'Glycerin Preservation',
		expectedPreservedLife: '2-3 years',
		colorCategory: 'White',
		rating: 4.7,
		tags: ['fragrant', 'delicate', 'traditional'],
		season: 'Summer',
		availability: true
	}),
	buildFlower({
		id: 'daisy-shasta',
		commonName: 'Shasta Daisy',
		botanicalName: 'Leucanthemum × superbum',
		scientificName: 'Leucanthemum × superbum',
		category: 'Wildflower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Blue Mountain Botanicals',
		country: 'India',
		availableStock: 430,
		remainingStock: 371,
		price: 139,
		description:
			'Clean white petals around a golden center; presses flat with crisp, graphic results for framed keepsakes.',
		preservationMethod: 'Pressed Preservation',
		expectedPreservedLife: '3+ years',
		colorCategory: 'White',
		rating: 4.5,
		tags: ['simple', 'cheerful', 'framed-art'],
		season: 'Summer',
		availability: true
	}),
	buildFlower({
		id: 'anemone',
		commonName: 'Anemone',
		botanicalName: 'Anemone coronaria',
		scientificName: 'Anemone coronaria',
		category: 'Wildflower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Himalayan Peony Growers',
		country: 'India',
		availableStock: 220,
		remainingStock: 168,
		price: 379,
		description:
			'Striking dark centers with silky, poppy-like petals; a favorite in modern minimalist keepsake design.',
		preservationMethod: 'Silica Gel Drying',
		expectedPreservedLife: '3 years',
		colorCategory: 'Purple',
		rating: 4.7,
		tags: ['modern', 'striking', 'minimalist'],
		season: 'Spring',
		availability: true
	}),
	buildFlower({
		id: 'ranunculus',
		commonName: 'Ranunculus',
		botanicalName: 'Ranunculus asiaticus',
		scientificName: 'Ranunculus asiaticus',
		category: 'Rose Family',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Himalayan Peony Growers',
		country: 'India',
		availableStock: 260,
		remainingStock: 201,
		price: 419,
		description:
			'Tightly layered, paper-thin petals resembling a rose — a top choice for silica-dried statement keepsakes.',
		preservationMethod: 'Silica Gel Drying',
		expectedPreservedLife: '3-4 years',
		colorCategory: 'Orange',
		rating: 4.8,
		tags: ['layered', 'premium', 'wedding'],
		season: 'Spring',
		availability: true
	}),
	buildFlower({
		id: 'freesia',
		commonName: 'Freesia',
		botanicalName: 'Freesia refracta',
		scientificName: 'Freesia refracta',
		category: 'Bulb Flower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Kashmir Bulb Gardens',
		country: 'India',
		availableStock: 300,
		remainingStock: 245,
		price: 259,
		description:
			'Trumpet-shaped, sweetly scented blooms along a slender stem, well suited for pressed botanical layouts.',
		preservationMethod: 'Pressed Preservation',
		expectedPreservedLife: '3 years',
		colorCategory: 'Yellow',
		rating: 4.5,
		tags: ['fragrant', 'delicate', 'linear'],
		season: 'Spring',
		availability: true
	}),
	buildFlower({
		id: 'gerbera',
		commonName: 'Gerbera Daisy',
		botanicalName: 'Gerbera jamesonii',
		scientificName: 'Gerbera jamesonii',
		category: 'Wildflower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Deccan Flower Farms',
		country: 'India',
		availableStock: 390,
		remainingStock: 320,
		price: 219,
		description:
			'Bright, bold blooms in saturated colors; freeze-drying keeps the flat, graphic petal form intact.',
		preservationMethod: 'Freeze-Drying',
		expectedPreservedLife: '3 years',
		colorCategory: 'Orange',
		rating: 4.6,
		tags: ['bold', 'colorful', 'cheerful'],
		season: 'Year-Round',
		availability: true
	}),
	buildFlower({
		id: 'delphinium',
		commonName: 'Delphinium',
		botanicalName: 'Delphinium elatum',
		scientificName: 'Delphinium elatum',
		category: 'Wildflower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Blue Mountain Botanicals',
		country: 'India',
		availableStock: 150,
		remainingStock: 104,
		price: 329,
		description:
			'Tall spikes of vivid blue florets, dried whole for dramatic vertical elements in large keepsake frames.',
		preservationMethod: 'Pressed Preservation',
		expectedPreservedLife: '3-4 years',
		colorCategory: 'Blue',
		rating: 4.7,
		tags: ['dramatic', 'vertical', 'statement'],
		season: 'Summer',
		availability: true
	}),
	buildFlower({
		id: 'protea',
		commonName: 'Protea',
		botanicalName: 'Protea cynaroides',
		scientificName: 'Protea cynaroides',
		category: 'Tropical',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Western Ghats Orchidarium',
		country: 'India',
		availableStock: 90,
		remainingStock: 61,
		price: 899,
		description:
			'A dramatic, architectural bloom with naturally sturdy bracts that dry exceptionally well with minimal shrinkage.',
		preservationMethod: 'Silica Gel Drying',
		expectedPreservedLife: '5+ years',
		colorCategory: 'Pink',
		rating: 4.9,
		tags: ['architectural', 'luxury', 'rare'],
		season: 'Winter',
		availability: true
	}),
	buildFlower({
		id: 'eucalyptus',
		commonName: 'Eucalyptus',
		botanicalName: 'Eucalyptus cinerea',
		scientificName: 'Eucalyptus cinerea',
		category: 'Filler Flower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Blue Mountain Botanicals',
		country: 'India',
		availableStock: 650,
		remainingStock: 588,
		price: 119,
		description:
			'Silvery-green rounded foliage that air-dries naturally and holds shape for years, a staple filler in keepsake compositions.',
		preservationMethod: 'Pressed Preservation',
		expectedPreservedLife: '5+ years',
		colorCategory: 'Mixed',
		rating: 4.6,
		tags: ['greenery', 'filler', 'aromatic'],
		season: 'Year-Round',
		availability: true
	}),
	buildFlower({
		id: 'cornflower',
		commonName: 'Cornflower',
		botanicalName: 'Centaurea cyanus',
		scientificName: 'Centaurea cyanus',
		category: 'Wildflower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Deccan Flower Farms',
		country: 'India',
		availableStock: 480,
		remainingStock: 412,
		price: 109,
		description:
			'Vivid true-blue fringed petals that retain their rare color exceptionally well when air-dried.',
		preservationMethod: 'Pressed Preservation',
		expectedPreservedLife: '4 years',
		colorCategory: 'Blue',
		rating: 4.5,
		tags: ['rare-color', 'wildflower', 'accent'],
		season: 'Summer',
		availability: true
	}),
	buildFlower({
		id: 'zinnia',
		commonName: 'Zinnia',
		botanicalName: 'Zinnia elegans',
		scientificName: 'Zinnia elegans',
		category: 'Wildflower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Deccan Flower Farms',
		country: 'India',
		availableStock: 520,
		remainingStock: 449,
		price: 149,
		description:
			'Sturdy, multi-layered petals in vibrant hues, one of the most forgiving flowers for first-time preservation projects.',
		preservationMethod: 'Silica Gel Drying',
		expectedPreservedLife: '3 years',
		colorCategory: 'Mixed',
		rating: 4.4,
		tags: ['vibrant', 'sturdy', 'beginner-friendly'],
		season: 'Summer',
		availability: true
	}),
	buildFlower({
		id: 'iris',
		commonName: 'Iris',
		botanicalName: 'Iris germanica',
		scientificName: 'Iris germanica',
		category: 'Bulb Flower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Kashmir Bulb Gardens',
		country: 'India',
		availableStock: 200,
		remainingStock: 142,
		price: 299,
		description:
			'Elegant, ruffled falls and standards in deep purple tones; pressed flat, they yield striking flat-art keepsakes.',
		preservationMethod: 'Pressed Preservation',
		expectedPreservedLife: '3 years',
		colorCategory: 'Purple',
		rating: 4.6,
		tags: ['elegant', 'deep-color', 'framed-art'],
		season: 'Spring',
		availability: true
	}),
	buildFlower({
		id: 'lisianthus',
		commonName: 'Lisianthus',
		botanicalName: 'Eustoma grandiflorum',
		scientificName: 'Eustoma grandiflorum',
		category: 'Rose Family',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Himalayan Peony Growers',
		country: 'India',
		availableStock: 240,
		remainingStock: 176,
		price: 389,
		description:
			'Delicate, rose-like ruffled petals with a papery texture that preserves beautifully with gentle silica drying.',
		preservationMethod: 'Silica Gel Drying',
		expectedPreservedLife: '3-4 years',
		colorCategory: 'White',
		rating: 4.7,
		tags: ['delicate', 'romantic', 'wedding'],
		season: 'Summer',
		availability: true
	}),
	buildFlower({
		id: 'sweet-pea',
		commonName: 'Sweet Pea',
		botanicalName: 'Lathyrus odoratus',
		scientificName: 'Lathyrus odoratus',
		category: 'Wildflower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Blue Mountain Botanicals',
		country: 'India',
		availableStock: 280,
		remainingStock: 219,
		price: 199,
		description:
			'Ruffled, translucent petals with a light fragrance, best suited to careful pressing to retain their delicate frills.',
		preservationMethod: 'Pressed Preservation',
		expectedPreservedLife: '2-3 years',
		colorCategory: 'Pink',
		rating: 4.5,
		tags: ['fragrant', 'vintage', 'delicate'],
		season: 'Spring',
		availability: true
	}),
	buildFlower({
		id: 'amaranthus',
		commonName: 'Love-Lies-Bleeding',
		botanicalName: 'Amaranthus caudatus',
		scientificName: 'Amaranthus caudatus',
		category: 'Everlasting',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Deccan Flower Farms',
		country: 'India',
		availableStock: 260,
		remainingStock: 202,
		price: 179,
		description:
			'Long, cascading crimson tassels that dry naturally with striking drape, ideal for dramatic hanging keepsake designs.',
		preservationMethod: 'Pressed Preservation',
		expectedPreservedLife: '4 years',
		colorCategory: 'Red',
		rating: 4.6,
		tags: ['dramatic', 'cascading', 'unique'],
		season: 'Autumn',
		availability: true
	}),
	buildFlower({
		id: 'globe-amaranth',
		commonName: 'Globe Amaranth',
		botanicalName: 'Gomphrena globosa',
		scientificName: 'Gomphrena globosa',
		category: 'Everlasting',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Deccan Flower Farms',
		country: 'India',
		availableStock: 610,
		remainingStock: 540,
		price: 99,
		description:
			'True clover-shaped everlasting blooms that require virtually no processing to retain their color for years.',
		preservationMethod: 'Pressed Preservation',
		expectedPreservedLife: '5+ years',
		colorCategory: 'Purple',
		rating: 4.4,
		tags: ['everlasting', 'low-maintenance', 'budget'],
		season: 'Year-Round',
		availability: true
	}),
	buildFlower({
		id: 'queen-annes-lace',
		commonName: "Queen Anne's Lace",
		botanicalName: 'Daucus carota',
		scientificName: 'Daucus carota',
		category: 'Filler Flower',
		manufacturer: 'Flora Fusion Preservation Studio',
		supplier: 'Blue Mountain Botanicals',
		country: 'India',
		availableStock: 400,
		remainingStock: 336,
		price: 119,
		description:
			'Intricate, lacy white umbels that press into delicate botanical patterns, popular for fine art keepsake frames.',
		preservationMethod: 'Pressed Preservation',
		expectedPreservedLife: '3-4 years',
		colorCategory: 'White',
		rating: 4.5,
		tags: ['lace', 'intricate', 'botanical-art'],
		season: 'Summer',
		availability: true
	})
];

export const TOTAL_FLOWER_SLOTS = 30;

export function getAvailableFlowerCount(flowers: Flower[] = FLOWERS): number {
	return flowers.filter((f) => f.availability && f.remainingStock > 0).length;
}
