import type { Product } from '$lib/types/product';
import productImages from '../../../flora-fusion-images.json';

/**
 * PRODUCT IMAGE SOURCING NOTE:
 * mainImage resolves to the catalog photo hosted on Cloudinary (see
 * flora-fusion-images.json at the project root), so the keepsakes grid
 * displays real images with no Firebase Storage upload step required.
 */
function buildProduct(base: Omit<Product, 'mainImage' | 'gallery'>): Product {
	const image = (productImages.products as Record<string, string>)[base.id] ?? '';

	return {
		...base,
		mainImage: image,
		gallery: []
	};
}

export const PRODUCTS: Product[] = [
	buildProduct({
		id: 'resin-frame-small-classic',
		name: 'Classic Small Resin Frame (5x7")',
		slug: 'classic-small-resin-frame-5x7',
		category: 'Resin Frames',
		price: 1499,
		compareAtPrice: 1799,
		minFlowerWeightGrams: 20,
		maxFlowerWeightGrams: 80,
		productionDays: 7,
		workflow: 'Standard',
		description:
			'A compact resin-cast frame that suspends your preserved flowers in crystal-clear resin, finished with a matte wood border. Perfect for single stems or small posies.',
		shortDescription: 'Compact resin frame for small bouquets.',
		inventory: { inStock: true, quantityAvailable: 42, restockDate: null },
		rating: 4.8,
		reviewCount: 126,
		tags: ['bestseller', 'wedding', 'gift'],
		isFeatured: true,
		isCustomizable: true
	}),
	buildProduct({
		id: 'resin-frame-small-oak',
		name: 'Oak-Edge Small Resin Frame (5x7")',
		slug: 'oak-edge-small-resin-frame-5x7',
		category: 'Resin Frames',
		price: 1699,
		compareAtPrice: null,
		minFlowerWeightGrams: 20,
		maxFlowerWeightGrams: 80,
		productionDays: 7,
		workflow: 'Standard',
		description: 'The same beloved small resin frame with a solid oak edge for a warmer, more natural finish.',
		shortDescription: 'Small resin frame with oak trim.',
		inventory: { inStock: true, quantityAvailable: 30, restockDate: null },
		rating: 4.7,
		reviewCount: 58,
		tags: ['natural', 'gift'],
		isFeatured: false,
		isCustomizable: true
	}),
	buildProduct({
		id: 'resin-frame-large-statement',
		name: 'Statement Large Resin Frame (11x14")',
		slug: 'statement-large-resin-frame-11x14',
		category: 'Resin Frames',
		price: 2999,
		compareAtPrice: 3499,
		minFlowerWeightGrams: 60,
		maxFlowerWeightGrams: 250,
		productionDays: 10,
		workflow: 'Custom Design',
		description:
			'Our most popular full-bouquet preservation piece. A large-format resin frame designed to showcase an entire wedding or memorial bouquet in stunning detail.',
		shortDescription: 'Large resin frame for full bouquets.',
		inventory: { inStock: true, quantityAvailable: 18, restockDate: null },
		rating: 4.9,
		reviewCount: 214,
		tags: ['bestseller', 'wedding', 'memorial', 'statement'],
		isFeatured: true,
		isCustomizable: true
	}),
	buildProduct({
		id: 'resin-frame-large-gold',
		name: 'Gold-Leaf Large Resin Frame (11x14")',
		slug: 'gold-leaf-large-resin-frame-11x14',
		category: 'Resin Frames',
		price: 3499,
		compareAtPrice: null,
		minFlowerWeightGrams: 60,
		maxFlowerWeightGrams: 250,
		productionDays: 11,
		workflow: 'Custom Design',
		description: 'A luxurious take on our large resin frame, finished with delicate gold-leaf accents around the border.',
		shortDescription: 'Large resin frame with gold-leaf trim.',
		inventory: { inStock: true, quantityAvailable: 12, restockDate: null },
		rating: 4.9,
		reviewCount: 71,
		tags: ['luxury', 'wedding', 'anniversary'],
		isFeatured: true,
		isCustomizable: true
	}),
	buildProduct({
		id: 'resin-dome-classic',
		name: 'Classic Resin Dome',
		slug: 'classic-resin-dome',
		category: 'Resin Domes',
		price: 1299,
		compareAtPrice: null,
		minFlowerWeightGrams: 15,
		maxFlowerWeightGrams: 60,
		productionDays: 6,
		workflow: 'Standard',
		description: 'A glass-like dome that preserves your blooms in three dimensions, displayed on a wooden base.',
		shortDescription: 'Three-dimensional resin dome display.',
		inventory: { inStock: true, quantityAvailable: 55, restockDate: null },
		rating: 4.6,
		reviewCount: 89,
		tags: ['everyday', 'gift'],
		isFeatured: false,
		isCustomizable: true
	}),
	buildProduct({
		id: 'resin-dome-nightlight',
		name: 'Resin Dome Night Light',
		slug: 'resin-dome-night-light',
		category: 'Resin Domes',
		price: 1899,
		compareAtPrice: null,
		minFlowerWeightGrams: 15,
		maxFlowerWeightGrams: 60,
		productionDays: 8,
		workflow: 'Custom Design',
		description: 'A resin dome fitted with a warm LED base, illuminating your preserved flowers after dark.',
		shortDescription: 'Illuminated resin dome with LED base.',
		inventory: { inStock: true, quantityAvailable: 24, restockDate: null },
		rating: 4.8,
		reviewCount: 63,
		tags: ['unique', 'gift', 'night-light'],
		isFeatured: true,
		isCustomizable: true
	}),
	buildProduct({
		id: 'jewelry-pendant-round',
		name: 'Round Botanical Pendant Necklace',
		slug: 'round-botanical-pendant-necklace',
		category: 'Jewelry',
		price: 899,
		compareAtPrice: null,
		minFlowerWeightGrams: 1,
		maxFlowerWeightGrams: 10,
		productionDays: 5,
		workflow: 'Standard',
		description: 'A delicate round pendant encasing a single petal or small bloom fragment on a sterling silver chain.',
		shortDescription: 'Round pendant with sterling silver chain.',
		inventory: { inStock: true, quantityAvailable: 90, restockDate: null },
		rating: 4.7,
		reviewCount: 152,
		tags: ['jewelry', 'gift', 'everyday'],
		isFeatured: true,
		isCustomizable: true
	}),
	buildProduct({
		id: 'jewelry-pendant-teardrop',
		name: 'Teardrop Botanical Pendant Necklace',
		slug: 'teardrop-botanical-pendant-necklace',
		category: 'Jewelry',
		price: 949,
		compareAtPrice: null,
		minFlowerWeightGrams: 1,
		maxFlowerWeightGrams: 10,
		productionDays: 5,
		workflow: 'Standard',
		description: 'An elegant teardrop-shaped pendant, ideal for showcasing a single flower petal or small fern leaf.',
		shortDescription: 'Teardrop pendant necklace.',
		inventory: { inStock: true, quantityAvailable: 70, restockDate: null },
		rating: 4.6,
		reviewCount: 84,
		tags: ['jewelry', 'gift'],
		isFeatured: false,
		isCustomizable: true
	}),
	buildProduct({
		id: 'jewelry-earrings-stud',
		name: 'Botanical Stud Earrings (Pair)',
		slug: 'botanical-stud-earrings-pair',
		category: 'Jewelry',
		price: 799,
		compareAtPrice: null,
		minFlowerWeightGrams: 1,
		maxFlowerWeightGrams: 6,
		productionDays: 5,
		workflow: 'Standard',
		description: 'A matching pair of stud earrings featuring tiny preserved petals set in resin.',
		shortDescription: 'Preserved petal stud earrings.',
		inventory: { inStock: true, quantityAvailable: 65, restockDate: null },
		rating: 4.5,
		reviewCount: 47,
		tags: ['jewelry', 'gift', 'everyday'],
		isFeatured: false,
		isCustomizable: true
	}),
	buildProduct({
		id: 'jewelry-bracelet-charm',
		name: 'Botanical Charm Bracelet',
		slug: 'botanical-charm-bracelet',
		category: 'Jewelry',
		price: 1099,
		compareAtPrice: null,
		minFlowerWeightGrams: 1,
		maxFlowerWeightGrams: 8,
		productionDays: 6,
		workflow: 'Standard',
		description: 'A dainty chain bracelet featuring a single resin-set charm made from your preserved flowers.',
		shortDescription: 'Chain bracelet with botanical charm.',
		inventory: { inStock: true, quantityAvailable: 40, restockDate: null },
		rating: 4.6,
		reviewCount: 39,
		tags: ['jewelry', 'gift'],
		isFeatured: false,
		isCustomizable: true
	}),
	buildProduct({
		id: 'keepsake-box-classic',
		name: 'Classic Preserved Keepsake Box',
		slug: 'classic-preserved-keepsake-box',
		category: 'Keepsake Boxes',
		price: 2199,
		compareAtPrice: null,
		minFlowerWeightGrams: 40,
		maxFlowerWeightGrams: 300,
		productionDays: 9,
		workflow: 'Standard',
		description: 'A velvet-lined wooden box displaying your dried blooms beneath a glass viewing lid.',
		shortDescription: 'Velvet-lined keepsake display box.',
		inventory: { inStock: true, quantityAvailable: 26, restockDate: null },
		rating: 4.7,
		reviewCount: 98,
		tags: ['memorial', 'anniversary', 'gift'],
		isFeatured: true,
		isCustomizable: true
	}),
	buildProduct({
		id: 'keepsake-box-memorial',
		name: 'Memorial Tribute Keepsake Box',
		slug: 'memorial-tribute-keepsake-box',
		category: 'Keepsake Boxes',
		price: 2599,
		compareAtPrice: null,
		minFlowerWeightGrams: 40,
		maxFlowerWeightGrams: 300,
		productionDays: 10,
		workflow: 'Custom Design',
		description: 'A thoughtfully designed keepsake box with an engraved nameplate option, created for memorial tributes.',
		shortDescription: 'Engravable memorial keepsake box.',
		inventory: { inStock: true, quantityAvailable: 20, restockDate: null },
		rating: 4.9,
		reviewCount: 112,
		tags: ['memorial', 'sympathy', 'engraving'],
		isFeatured: true,
		isCustomizable: true
	}),
	buildProduct({
		id: 'pressed-art-frame-a4',
		name: 'Pressed Botanical Art Frame (A4)',
		slug: 'pressed-botanical-art-frame-a4',
		category: 'Pressed Art',
		price: 1799,
		compareAtPrice: null,
		minFlowerWeightGrams: 10,
		maxFlowerWeightGrams: 100,
		productionDays: 8,
		workflow: 'Standard',
		description: 'Flat-pressed flowers arranged into fine botanical art, framed behind UV-protective glass.',
		shortDescription: 'Framed pressed-flower botanical art.',
		inventory: { inStock: true, quantityAvailable: 38, restockDate: null },
		rating: 4.6,
		reviewCount: 74,
		tags: ['wall-art', 'gift'],
		isFeatured: false,
		isCustomizable: true
	}),
	buildProduct({
		id: 'pressed-art-frame-a3',
		name: 'Pressed Botanical Art Frame (A3)',
		slug: 'pressed-botanical-art-frame-a3',
		category: 'Pressed Art',
		price: 2299,
		compareAtPrice: null,
		minFlowerWeightGrams: 20,
		maxFlowerWeightGrams: 100,
		productionDays: 9,
		workflow: 'Standard',
		description: 'A larger canvas for pressed botanical art, ideal for statement bouquets and multi-flower arrangements.',
		shortDescription: 'Large framed pressed-flower art.',
		inventory: { inStock: true, quantityAvailable: 22, restockDate: null },
		rating: 4.7,
		reviewCount: 41,
		tags: ['wall-art', 'statement'],
		isFeatured: false,
		isCustomizable: true
	}),
	buildProduct({
		id: 'pressed-art-diptych',
		name: 'Pressed Botanical Diptych Set',
		slug: 'pressed-botanical-diptych-set',
		category: 'Pressed Art',
		price: 3199,
		compareAtPrice: 3599,
		minFlowerWeightGrams: 20,
		maxFlowerWeightGrams: 120,
		productionDays: 10,
		workflow: 'Custom Design',
		description: 'A matching two-frame set that splits your bouquet into a striking side-by-side botanical display.',
		shortDescription: 'Two-frame pressed art set.',
		inventory: { inStock: true, quantityAvailable: 14, restockDate: null },
		rating: 4.8,
		reviewCount: 33,
		tags: ['wall-art', 'wedding', 'set'],
		isFeatured: true,
		isCustomizable: true
	}),
	buildProduct({
		id: 'shadow-box-standard',
		name: 'Dimensional Shadow Box',
		slug: 'dimensional-shadow-box',
		category: 'Shadow Boxes',
		price: 3499,
		compareAtPrice: null,
		minFlowerWeightGrams: 80,
		maxFlowerWeightGrams: 400,
		productionDays: 12,
		workflow: 'Custom Design',
		description: 'A deep-set display box that preserves your full bouquet in dimension, alongside optional keepsakes like invitations or ribbon.',
		shortDescription: 'Deep-set full-bouquet display box.',
		inventory: { inStock: true, quantityAvailable: 16, restockDate: null },
		rating: 4.9,
		reviewCount: 87,
		tags: ['wedding', 'statement', 'memorabilia'],
		isFeatured: true,
		isCustomizable: true
	}),
	buildProduct({
		id: 'shadow-box-military',
		name: 'Tribute Shadow Box (Large)',
		slug: 'tribute-shadow-box-large',
		category: 'Shadow Boxes',
		price: 3999,
		compareAtPrice: null,
		minFlowerWeightGrams: 100,
		maxFlowerWeightGrams: 400,
		productionDays: 13,
		workflow: 'Custom Design',
		description: 'An extra-large tribute shadow box designed to hold flowers alongside photos or small memorabilia.',
		shortDescription: 'Extra-large tribute display box.',
		inventory: { inStock: true, quantityAvailable: 10, restockDate: null },
		rating: 4.9,
		reviewCount: 29,
		tags: ['memorial', 'tribute', 'statement'],
		isFeatured: false,
		isCustomizable: true
	}),
	buildProduct({
		id: 'ornament-glass-round',
		name: 'Round Glass Flower Ornament',
		slug: 'round-glass-flower-ornament',
		category: 'Ornaments',
		price: 699,
		compareAtPrice: null,
		minFlowerWeightGrams: 5,
		maxFlowerWeightGrams: 25,
		productionDays: 5,
		workflow: 'Standard',
		description: 'A hanging round glass ornament filled with preserved petals — a lovely gift or keepsake tree decoration.',
		shortDescription: 'Hanging glass ornament with petals.',
		inventory: { inStock: true, quantityAvailable: 80, restockDate: null },
		rating: 4.5,
		reviewCount: 66,
		tags: ['gift', 'ornament', 'affordable'],
		isFeatured: false,
		isCustomizable: true
	}),
	buildProduct({
		id: 'ornament-glass-heart',
		name: 'Heart Glass Flower Ornament',
		slug: 'heart-glass-flower-ornament',
		category: 'Ornaments',
		price: 749,
		compareAtPrice: null,
		minFlowerWeightGrams: 5,
		maxFlowerWeightGrams: 25,
		productionDays: 5,
		workflow: 'Standard',
		description: 'A heart-shaped glass ornament capturing preserved petals, popular for anniversary and Valentine gifts.',
		shortDescription: 'Heart-shaped glass ornament.',
		inventory: { inStock: true, quantityAvailable: 74, restockDate: null },
		rating: 4.6,
		reviewCount: 52,
		tags: ['gift', 'romantic', 'anniversary'],
		isFeatured: false,
		isCustomizable: true
	}),
	buildProduct({
		id: 'coaster-set-resin',
		name: 'Botanical Resin Coaster Set (4pc)',
		slug: 'botanical-resin-coaster-set-4pc',
		category: 'Home Decor',
		price: 1299,
		compareAtPrice: null,
		minFlowerWeightGrams: 10,
		maxFlowerWeightGrams: 60,
		productionDays: 7,
		workflow: 'Standard',
		description: 'A set of four resin coasters, each featuring a different preserved flower from your submission.',
		shortDescription: 'Set of four resin flower coasters.',
		inventory: { inStock: true, quantityAvailable: 46, restockDate: null },
		rating: 4.7,
		reviewCount: 61,
		tags: ['home-decor', 'gift', 'set'],
		isFeatured: false,
		isCustomizable: true
	}),
	buildProduct({
		id: 'bookmark-resin',
		name: 'Preserved Flower Resin Bookmark',
		slug: 'preserved-flower-resin-bookmark',
		category: 'Home Decor',
		price: 449,
		compareAtPrice: null,
		minFlowerWeightGrams: 2,
		maxFlowerWeightGrams: 15,
		productionDays: 4,
		workflow: 'Standard',
		description: 'A slim resin bookmark with a tassel, showcasing a small preserved flower or leaf.',
		shortDescription: 'Resin bookmark with tassel.',
		inventory: { inStock: true, quantityAvailable: 120, restockDate: null },
		rating: 4.4,
		reviewCount: 88,
		tags: ['affordable', 'gift', 'stationery'],
		isFeatured: false,
		isCustomizable: true
	}),
	buildProduct({
		id: 'phone-case-resin',
		name: 'Custom Botanical Phone Case',
		slug: 'custom-botanical-phone-case',
		category: 'Home Decor',
		price: 999,
		compareAtPrice: null,
		minFlowerWeightGrams: 5,
		maxFlowerWeightGrams: 30,
		productionDays: 8,
		workflow: 'Custom Design',
		description: 'A protective phone case embedded with preserved petals, made to order for popular phone models.',
		shortDescription: 'Phone case with preserved petals.',
		inventory: { inStock: true, quantityAvailable: 35, restockDate: null },
		rating: 4.3,
		reviewCount: 27,
		tags: ['tech', 'gift', 'custom'],
		isFeatured: false,
		isCustomizable: true
	}),
	buildProduct({
		id: 'wall-clock-resin',
		name: 'Botanical Resin Wall Clock',
		slug: 'botanical-resin-wall-clock',
		category: 'Home Decor',
		price: 2799,
		compareAtPrice: null,
		minFlowerWeightGrams: 30,
		maxFlowerWeightGrams: 150,
		productionDays: 11,
		workflow: 'Custom Design',
		description: 'A functioning wall clock with preserved flowers cast into its resin face — a striking statement piece.',
		shortDescription: 'Functional wall clock with embedded flowers.',
		inventory: { inStock: true, quantityAvailable: 15, restockDate: null },
		rating: 4.8,
		reviewCount: 22,
		tags: ['home-decor', 'unique', 'statement'],
		isFeatured: true,
		isCustomizable: true
	}),
	buildProduct({
		id: 'bulk-corporate-gift-set',
		name: 'Corporate Gifting Keepsake Set (Bulk)',
		slug: 'corporate-gifting-keepsake-set-bulk',
		category: 'Bulk Orders',
		price: 799,
		compareAtPrice: null,
		minFlowerWeightGrams: 5,
		maxFlowerWeightGrams: 25,
		productionDays: 14,
		workflow: 'Bulk Order',
		description: 'A per-unit priced keepsake ornament designed for corporate events, ideal for bulk orders of 20 or more.',
		shortDescription: 'Bulk-priced keepsake for corporate events.',
		inventory: { inStock: true, quantityAvailable: 500, restockDate: null },
		rating: 4.5,
		reviewCount: 19,
		tags: ['corporate', 'bulk', 'events'],
		isFeatured: false,
		isCustomizable: false
	}),
	buildProduct({
		id: 'rush-express-frame',
		name: 'Rush Express Small Resin Frame',
		slug: 'rush-express-small-resin-frame',
		category: 'Resin Frames',
		price: 2199,
		compareAtPrice: null,
		minFlowerWeightGrams: 20,
		maxFlowerWeightGrams: 80,
		productionDays: 3,
		workflow: 'Rush Production',
		description: 'Our classic small resin frame produced on an expedited 3-day rush timeline for last-minute gifting.',
		shortDescription: 'Expedited 3-day small resin frame.',
		inventory: { inStock: true, quantityAvailable: 20, restockDate: null },
		rating: 4.6,
		reviewCount: 34,
		tags: ['rush', 'gift', 'last-minute'],
		isFeatured: false,
		isCustomizable: true
	})
];

export const PRODUCT_CATEGORIES = Array.from(new Set(PRODUCTS.map((p) => p.category)));

export function getFeaturedProducts(count = 8): Product[] {
	return PRODUCTS.filter((p) => p.isFeatured).slice(0, count);
}
